[package]
name = "rust-first-web"
version = "0.1.0"
authors = ["Brian <tingsy@sains.com.my>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
chrono = "0.4.19"